function cleanKey(v){return String(v||'').trim().replace(/^Bearer\s+/i,'').replace(/^['\"]|['\"]$/g,'').trim()}

function fallbackQuestion(area,assunto,dificuldade){
 const bank=[
  {enunciado:'Sobre a cadeia de custódia prevista no Código de Processo Penal, assinale a alternativa correta.',alternativas:['A) Inicia-se apenas após o vestígio chegar ao laboratório.','B) Compreende o conjunto de procedimentos para manter e documentar a história cronológica do vestígio.','C) Aplica-se somente aos vestígios biológicos.','D) Dispensa registro quando o objeto é apreendido em flagrante.','E) Encerra-se obrigatoriamente com a elaboração do laudo.'],correta:'B',comentario:'A cadeia de custódia documenta a trajetória do vestígio desde o reconhecimento até o descarte, preservando rastreabilidade e confiabilidade. As demais alternativas restringem indevidamente sua extensão ou dispensam registros exigidos pelo CPP.',pegadinha:'Confundir cadeia de custódia com a fase exclusivamente laboratorial.',fundamento:'Código de Processo Penal, arts. 158-A a 158-F.'},
  {enunciado:'A respeito dos princípios da Administração Pública expressos na Constituição Federal, assinale a alternativa correta.',alternativas:['A) A eficiência substitui a legalidade quando houver urgência.','B) A publicidade é absoluta e não admite restrições.','C) Legalidade, impessoalidade, moralidade, publicidade e eficiência vinculam a Administração Pública.','D) A moralidade possui caráter apenas recomendatório.','E) A impessoalidade permite promoção pessoal custeada pelo poder público.'],correta:'C',comentario:'O art. 37, caput, da Constituição estabelece os princípios expressos da legalidade, impessoalidade, moralidade, publicidade e eficiência. Nenhum deles elimina os demais, e a publicidade admite restrições constitucionais e legais.',pegadinha:'Tratar os princípios como regras isoladas ou facultativas.',fundamento:'Constituição Federal, art. 37, caput.'},
  {enunciado:'No concurso de pessoas, assinale a alternativa correta de acordo com o Código Penal.',alternativas:['A) Todos respondem necessariamente pela mesma pena.','B) A participação de menor importância pode gerar diminuição de pena.','C) Circunstâncias pessoais sempre se comunicam aos demais agentes.','D) O ajuste e a instigação são sempre puníveis, mesmo sem tentativa.','E) A cooperação dolosamente distinta exclui qualquer responsabilização.'],correta:'B',comentario:'O Código Penal prevê diminuição de um sexto a um terço quando a participação for de menor importância. A pena é individualizada, circunstâncias pessoais não se comunicam salvo quando elementares, e atos preparatórios seguem a regra do art. 31.',pegadinha:'Confundir unidade do crime com identidade obrigatória de penas.',fundamento:'Código Penal, arts. 29 a 31.'},
  {enunciado:'Sobre os direitos e garantias fundamentais, assinale a alternativa correta.',alternativas:['A) A casa pode ser invadida por ordem administrativa a qualquer hora.','B) A prova ilícita é admitida quando o crime for grave.','C) Ninguém será privado da liberdade ou de seus bens sem o devido processo legal.','D) O contraditório existe apenas no processo judicial.','E) O direito de reunião depende de autorização prévia.'],correta:'C',comentario:'A Constituição assegura o devido processo legal. O contraditório alcança processos judicial e administrativo; a reunião independe de autorização, observados os requisitos constitucionais; e provas ilícitas são inadmissíveis.',pegadinha:'Trocar aviso prévio por autorização prévia no direito de reunião.',fundamento:'Constituição Federal, art. 5º, LIV e demais incisos pertinentes.'},
  {enunciado:'Na execução penal, a assistência ao preso e ao internado tem por finalidade:',alternativas:['A) Apenas prevenir fugas.','B) Somente garantir atendimento médico emergencial.','C) Prevenir o crime e orientar o retorno à convivência em sociedade.','D) Substituir integralmente a atuação da família.','E) Aplicar nova sanção disciplinar.'],correta:'C',comentario:'A assistência é dever do Estado e busca prevenir o crime e orientar o retorno à convivência em sociedade, abrangendo as modalidades previstas na LEP.',pegadinha:'Reduzir a assistência a uma única prestação material ou de saúde.',fundamento:'Lei de Execução Penal, arts. 10 e 11.'}
 ];
 const seed=(String(area)+String(assunto)+String(dificuldade)+new Date().toISOString().slice(0,10)).split('').reduce((a,c)=>a+c.charCodeAt(0),0);
 return {...bank[seed%bank.length],sources:[],provider:'mcp-continuity'};
}

const AREAS={geral:'carreiras policiais',civil:'Polícia Civil',penal:'Polícia Penal',cientifica:'Polícia Científica',gcm:'Guardas Municipais'};
const OFFICIAL=['stf.jus.br','portal.stf.jus.br','stj.jus.br','cnj.jus.br','planalto.gov.br','gov.br','senado.leg.br','camara.leg.br'];
function allowed(url){try{const h=new URL(url).hostname.toLowerCase();return OFFICIAL.some(d=>h===d||h.endsWith('.'+d))}catch{return false}}
function parseQuestion(text){const cleaned=String(text||'').trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim();const q=JSON.parse(cleaned);if(!q?.enunciado||!Array.isArray(q.alternativas)||q.alternativas.length<2||!q?.correta)throw new Error('Questão incompleta');return q}
export default async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'Método não permitido.'});
 const openaiKey=cleanKey(process.env.OPENAI_API_KEY),geminiKey=cleanKey(process.env.GEMINI_API_KEY),groqKey=cleanKey(process.env.GROQ_API_KEY),tavilyKey=cleanKey(process.env.TAVILY_API_KEY||process.env.TAVLY_API_KEY);
 if(!openaiKey&&!geminiKey&&!groqKey)return res.status(503).json({error:'IA de questões indisponível.'});
 const area=AREAS[req.body?.area]||AREAS.geral,assunto=String(req.body?.assunto||'conteúdo jurídico relevante').slice(0,120),banca=String(req.body?.banca||'estilo concursos policiais').slice(0,80),dificuldade=['fácil','médio','difícil'].includes(req.body?.dificuldade)?req.body.dificuldade:'médio';
 let context='',sources=[];
 if(tavilyKey){try{const r=await fetch('https://api.tavily.com/search',{method:'POST',headers:{Authorization:`Bearer ${tavilyKey}`,'Content-Type':'application/json'},body:JSON.stringify({query:`${assunto} ${area} legislação jurisprudência`,search_depth:'advanced',max_results:6,include_raw_content:false,include_domains:OFFICIAL,country:'brazil'})});const d=await r.json();if(r.ok){const valid=(d.results||[]).filter(x=>x?.url&&allowed(x.url));sources=valid.map(x=>({title:x.title||'Fonte oficial',url:x.url})).filter((x,i,a)=>a.findIndex(y=>y.url===x.url)===i).slice(0,4);context=valid.map(x=>String(x.content||'').trim()).filter(Boolean).slice(0,5).join('\n\n').slice(0,8000)}}catch(e){console.error('Tavily question error',e?.message)}}
 const prompt=`Crie UMA questão AUTORAL para concurso de ${area}. Assunto: ${assunto}. Estilo: ${banca}. Dificuldade: ${dificuldade}. Não copie questões existentes. Use o contexto oficial fornecido quando houver e não invente artigos, julgados ou números. Retorne SOMENTE JSON válido, sem markdown, no formato {"enunciado":"...","alternativas":["A) ...","B) ...","C) ...","D) ...","E) ..."],"correta":"A","comentario":"explicação completa do gabarito e por que as demais estão erradas","pegadinha":"...","fundamento":"lei/jurisprudência oficial usada"}. Não revele o gabarito no enunciado.${context?`\n\nCONTEXTO OFICIAL:\n${context}`:''}`;
 if(openaiKey){try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${openaiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5-mini',input:prompt,max_output_tokens:1500})});const d=await r.json();if(r.ok){const text=String(d.output_text||d.output?.flatMap(x=>x.content||[]).map(x=>x.text||'').join('')||'').trim();try{const q=parseQuestion(text);res.setHeader('Cache-Control','private, no-store');return res.status(200).json({...q,sources,provider:'openai'})}catch(e){console.error('OpenAI question parse failed',e?.message)}}else console.error('OpenAI question failed',r.status,String(d?.error?.message||'unknown').slice(0,180))}catch(e){console.error('OpenAI question error',e?.message)}}
 if(groqKey){try{const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${groqKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:'openai/gpt-oss-20b',messages:[{role:'user',content:prompt}],max_completion_tokens:1100,response_format:{type:'json_object'}})});const d=await r.json();if(r.ok){try{const q=parseQuestion(d?.choices?.[0]?.message?.content);res.setHeader('Cache-Control','private, no-store');return res.status(200).json({...q,sources,provider:'groq-gpt-oss-20b'})}catch(e){console.error('Groq question parse failed',e?.message)}}else console.error('Groq question failed',r.status,String(d?.error?.message||'unknown').slice(0,180))}catch(e){console.error('Groq question error',e?.message)}}
 if(geminiKey){try{const r=await fetch('https://generativelanguage.googleapis.com/v1beta/interactions',{method:'POST',headers:{'x-goog-api-key':geminiKey,'Content-Type':'application/json'},body:JSON.stringify({model:'gemini-3.6-flash',input:prompt,tools:context?[]:[{type:'google_search'}]})});const d=await r.json();if(r.ok){let text='';for(const step of d?.steps||[])if(step?.type==='model_output')for(const b of step.content||[])if(b?.type==='text'&&b.text)text+=b.text;try{const q=parseQuestion(text);res.setHeader('Cache-Control','private, no-store');return res.status(200).json({...q,sources,provider:'gemini'})}catch(e){console.error('Gemini question parse failed',e?.message)}}else console.error('Gemini question failed',r.status,String(d?.error?.message||'unknown').slice(0,180))}catch(e){console.error('Gemini question error',e?.message)}}
 return res.status(200).json(fallbackQuestion(area,assunto,dificuldade));
}
