function cleanKey(v){return String(v||'').trim().replace(/^Bearer\s+/i,'').replace(/^['\"]|['\"]$/g,'').trim()}
const AREAS={geral:'carreiras policiais',civil:'Polícia Civil',penal:'Polícia Penal',cientifica:'Polícia Científica',gcm:'Guardas Municipais'};
const OFFICIAL=['stf.jus.br','portal.stf.jus.br','stj.jus.br','cnj.jus.br','planalto.gov.br','gov.br','senado.leg.br','camara.leg.br'];
function allowed(url){try{const h=new URL(url).hostname.toLowerCase();return OFFICIAL.some(d=>h===d||h.endsWith('.'+d))}catch{return false}}
function parseQuestion(text){const cleaned=String(text||'').trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim();const q=JSON.parse(cleaned);if(!q?.enunciado||!Array.isArray(q.alternativas)||q.alternativas.length<2||!q?.correta)throw new Error('Questão incompleta');return q}
export default async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'Método não permitido.'});
 const geminiKey=cleanKey(process.env.GEMINI_API_KEY),groqKey=cleanKey(process.env.GROQ_API_KEY),tavilyKey=cleanKey(process.env.TAVILY_API_KEY||process.env.TAVLY_API_KEY);
 if(!geminiKey&&!groqKey)return res.status(503).json({error:'IA de questões indisponível.'});
 const area=AREAS[req.body?.area]||AREAS.geral,assunto=String(req.body?.assunto||'conteúdo jurídico relevante').slice(0,120),banca=String(req.body?.banca||'estilo concursos policiais').slice(0,80),dificuldade=['fácil','médio','difícil'].includes(req.body?.dificuldade)?req.body.dificuldade:'médio';
 let context='',sources=[];
 if(tavilyKey){try{const r=await fetch('https://api.tavily.com/search',{method:'POST',headers:{Authorization:`Bearer ${tavilyKey}`,'Content-Type':'application/json'},body:JSON.stringify({query:`${assunto} ${area} legislação jurisprudência`,search_depth:'advanced',max_results:6,include_raw_content:false,include_domains:OFFICIAL,country:'brazil'})});const d=await r.json();if(r.ok){const valid=(d.results||[]).filter(x=>x?.url&&allowed(x.url));sources=valid.map(x=>({title:x.title||'Fonte oficial',url:x.url})).filter((x,i,a)=>a.findIndex(y=>y.url===x.url)===i).slice(0,4);context=valid.map(x=>String(x.content||'').trim()).filter(Boolean).slice(0,5).join('\n\n').slice(0,8000)}}catch(e){console.error('Tavily question error',e?.message)}}
 const prompt=`Crie UMA questão AUTORAL para concurso de ${area}. Assunto: ${assunto}. Estilo: ${banca}. Dificuldade: ${dificuldade}. Não copie questões existentes. Use o contexto oficial fornecido quando houver e não invente artigos, julgados ou números. Retorne SOMENTE JSON válido, sem markdown, no formato {"enunciado":"...","alternativas":["A) ...","B) ...","C) ...","D) ...","E) ..."],"correta":"A","comentario":"explicação completa do gabarito e por que as demais estão erradas","pegadinha":"...","fundamento":"lei/jurisprudência oficial usada"}. Não revele o gabarito no enunciado.${context?`\n\nCONTEXTO OFICIAL:\n${context}`:''}`;
 if(groqKey){try{const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${groqKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:'openai/gpt-oss-20b',messages:[{role:'user',content:prompt}],max_completion_tokens:1100,response_format:{type:'json_object'}})});const d=await r.json();if(r.ok){try{const q=parseQuestion(d?.choices?.[0]?.message?.content);res.setHeader('Cache-Control','private, no-store');return res.status(200).json({...q,sources,provider:'groq-gpt-oss-20b'})}catch(e){console.error('Groq question parse failed',e?.message)}}else console.error('Groq question failed',r.status,String(d?.error?.message||'unknown').slice(0,180))}catch(e){console.error('Groq question error',e?.message)}}
 if(geminiKey){try{const r=await fetch('https://generativelanguage.googleapis.com/v1beta/interactions',{method:'POST',headers:{'x-goog-api-key':geminiKey,'Content-Type':'application/json'},body:JSON.stringify({model:'gemini-3.6-flash',input:prompt,tools:context?[]:[{type:'google_search'}]})});const d=await r.json();if(r.ok){let text='';for(const step of d?.steps||[])if(step?.type==='model_output')for(const b of step.content||[])if(b?.type==='text'&&b.text)text+=b.text;try{const q=parseQuestion(text);res.setHeader('Cache-Control','private, no-store');return res.status(200).json({...q,sources,provider:'gemini'})}catch(e){console.error('Gemini question parse failed',e?.message)}}else console.error('Gemini question failed',r.status,String(d?.error?.message||'unknown').slice(0,180))}catch(e){console.error('Gemini question error',e?.message)}}
 return res.status(502).json({error:'Falha ao gerar questão com as IAs disponíveis.'});
}
